"""Built-in documentation topics for `canary docs`."""

DOC_TOPICS = {
    "install": {
        "summary": "repo install commands and optional extras",
        "lines": [
            "  pip install .",
            "  pip install \".[local]\"",
            "  pip install -e \".[dev]\"",
            "",
            "  the package metadata currently installs the `canary` cli only.",
            "  use `.[local]` for on-device granite embeddings.",
        ],
    },
    "setup": {
        "summary": "guided backend setup and optional agent guard install",
        "lines": [
            "  canary setup",
            "  canary setup --prefer local",
            "  canary setup --prefer online",
            "  canary setup --guards yes",
            "",
            "  setup creates `.env` if needed, profiles the machine, selects a backend,",
            "  and can install guarded launch shims for supported AI coding agents in PATH.",
        ],
    },
    "prompt": {
        "summary": "direct prompt review",
        "lines": [
            "  canary prompt \"fix the login bug\"",
            "  canary prompt \"my key is sk-abc123xyzDEFGHIJKLMNOPQRSTUVWXYZ\" --strict",
            "",
            "  scans for secrets, pii, sensitive paths, and semantic matches",
            "  before you hand the text to an agent.",
            "  when the score reaches 35% or higher, Canary also renders a risk assessment panel.",
        ],
    },
    "screening": {
        "summary": "toggle guarded agent prompt screening",
        "lines": [
            "  canary on",
            "  canary off",
            "",
            "  works with the supported launch shims from `canary guard install`.",
            "  `canary on` opens the protected launch surface.",
            "  inside that window, type `:` to search commands like `:docs`, `:usage`, `:guard`, and `:watch`.",
            "  deeper session coverage is available when the installed agent exposes it.",
            "  a risk assessment panel appears automatically at 35% or higher.",
            "  use `--ignore` to bypass once or `--safe` to force screening once.",
        ],
    },
    "audit": {
        "summary": "live safety feed for agent tool activity",
        "lines": [
            "  canary audit",
            "  canary audit --background",
            "  canary audit --log",
            "  canary audit --stop",
            "",
            "  open another terminal window, tab, or split pane first.",
            "  in that second terminal, run `canary audit` and leave it open.",
            "  in your main terminal, start your AI coding agent or `canary watch .`.",
            "  use --background only if you want the older log + pid workflow.",
            "  the live feed shows pending bash approvals plus write/edit and output scans.",
            "  online mode uses granite chat for bash auditing; local mode uses pattern rules.",
        ],
    },
    "watch": {
        "summary": "protected launch surface and repo drift monitor",
        "lines": [
            "  canary watch .",
            "  canary watch . --prompt \"fix the login bug\"",
            "  canary watch . --background",
            "  canary watch . --continuous",
            "  canary watch --log",
            "  canary watch --stop",
            "",
            "  open `canary audit` in another terminal first if you want the live safety feed beside the launch surface.",
            "  then run `canary watch .` in your main terminal and enter the task at the protected prompt.",
            "  type `:` to search the in-window command palette without leaving Canary.",
            "  Canary screens that task first, and scores of 35% or higher get a risk assessment panel.",
            "  use --background for monitor-only mode; both paths create checkpoints and watch drift.",
        ],
    },
    "checkpoints": {
        "summary": "snapshots, rollback, and session logs",
        "lines": [
            "  canary checkpoint . --name before-auth",
            "  canary checkpoints .",
            "  canary rollback .",
            "  canary log . --tail 20",
            "",
            "  checkpoints live under `.canary/checkpoints/` inside the target repo.",
            "  `rollback` creates a backup snapshot before restoring.",
        ],
    },
    "backends": {
        "summary": "online watsonx.ai vs local granite embeddings",
        "lines": [
            "  canary mode status",
            "  canary mode local",
            "  canary mode online",
            "",
            "  online mode uses ibm watsonx.ai for embeddings and command auditing.",
            "  local mode uses hugging face + torch for embeddings and warns on slow devices.",
        ],
    },
    "guard": {
        "summary": "direct agent integration",
        "lines": [
            "  canary guard install",
            "  canary guard install --watch",
            "  canary guard status",
            "  canary guard remove",
            "  export PATH=\"$HOME/.canary/bin:$PATH\"",
            "",
            "  installs guarded launch shims for supported AI coding agents in PATH.",
            "  some agents can also expose extra session coverage through local settings.",
            "  launch-time prompt screening is available once the shims are installed.",
        ],
    },
    "usage": {
        "summary": "daily soft limits for online ibm usage",
        "lines": [
            "  canary usage",
            "",
            "  tracks daily text-generation and embedding calls in `~/.canary/usage.json`.",
            "  override limits with CANARY_GENERATE_LIMIT and CANARY_EMBED_LIMIT.",
        ],
    },
}
