"""Built-in documentation topics for `canary docs`."""

DOC_TOPICS = {
    "install": {
        "summary": "repo install commands and optional extras",
        "lines": [
            "  pip install .",
            "  pip install \".[local]\"",
            "  pip install -e \".[dev]\"",
            "",
            "  the package metadata currently installs the `canary` cli only.",
            "  canary now assumes local IBM Granite runtime only.",
        ],
    },
    "setup": {
        "summary": "guided local IBM Granite setup and optional protected shims",
        "lines": [
            "  canary setup",
            "  canary setup --prefer local",
            "  canary setup --guards yes",
            "",
            "  setup creates `.env` if needed, enables local IBM Granite,",
            "  installs local model support, and can install protected `claude` / `codex` shims.",
        ],
    },
    "prompt": {
        "summary": "interactive shell prompt behavior",
        "lines": [
            "  canary",
            "  hello, review this repo and fix the failing auth flow",
            "  /off",
            "  /on",
            "",
            "  type a prompt inside the canary shell to launch it through screening.",
            "  screening starts on, and only turns off when you run `/off`.",
            "  set CANARY_ALLOW_PARALLEL_TERMINALS=1 to prefer a second Terminal session on macOS.",
        ],
    },
    "screening": {
        "summary": "toggle guarded prompt screening",
        "lines": [
            "  canary on",
            "  canary off",
            "",
            "  works with the interactive canary shell and installed protected shims.",
            "  `claude` gets extra in-session prompt hooks; `codex` gets launch-time screening plus `/audit` transcript coverage.",
        ],
    },
    "audit": {
        "summary": "second-terminal audit translator for risky tool activity",
        "lines": [
            "  /audit",
            "  /audit exit",
            "",
            "  canary audit",
            "  canary audit --log",
            "  canary audit --stop",
            "",
            "  inside the shell, `/audit` opens an inline live subprocess dashboard.",
            "  `canary audit` opens a second terminal on macOS when possible, then streams Bash / Write / Edit risk.",
            "  compatible transcript hints are read from `~/.claude/projects/` and `~/.codex/sessions/`.",
            "  local-only canary uses pattern-based Bash auditing with no hosted IBM calls.",
        ],
    },
    "watch": {
        "summary": "protected launcher and repo drift monitor",
        "lines": [
            "  /watch",
            "  /watch exit",
            "",
            "  canary watch .",
            "  canary watch . --prompt \"fix the login bug\"",
            "  canary watch . --background",
            "  canary watch . --continuous",
            "  canary watch --log",
            "  canary watch --stop",
            "",
            "  inside the shell, `/watch` opens an inline live subprocess panel.",
            "  opens a protected prompt surface by default, then launches the resolved agent and starts the watcher.",
            "  set CANARY_ALLOW_PARALLEL_TERMINALS=1 to prefer a second Terminal session on macOS once watch is armed.",
            "  use --background for monitor-only mode; both paths create checkpoints and watch drift.",
        ],
    },
    "checkpoints": {
        "summary": "snapshots, rollback, and session logs",
        "lines": [
            "  /checkpoint before-auth",
            "  /checkpoint before-auth delete",
            "",
            "  canary checkpoint . --name before-auth",
            "  canary checkpoints .",
            "  canary rollback .",
            "  canary log . --tail 20",
            "",
            "  checkpoints live under `.canary/checkpoints/` inside the target repo.",
            "  manual checkpoints now require explicit names.",
            "  `rollback` creates a backup snapshot before restoring.",
        ],
    },
    "guard": {
        "summary": "direct protected CLI integration",
        "lines": [
            "  canary guard install",
            "  canary guard install --watch",
            "  canary guard status",
            "  canary guard remove",
            "  export PATH=\"$HOME/.canary/bin:$PATH\"",
            "",
            "  installs protected `claude` and `codex` shims when those binaries are available.",
            "  Claude also receives prompt, permission, and tool hooks through `~/.claude/settings.json`.",
        ],
    },
    "usage": {
        "summary": "local runtime status kept for compatibility",
        "lines": [
            "  canary usage",
            "",
            "  shows whether local dependencies and the Granite model cache are ready.",
            "  canary no longer advertises a hosted IBM runtime in the shell.",
        ],
    },
}
